name: Build and Push Docker Image

on:
  push:
    branches:
      - main    # Run the workflow on pushes to the main branch (modify as needed)

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
